# Generated by Django 4.1 on 2023-03-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="owner_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pay_per_hour",
            field=models.IntegerField(default=1000),
        ),
    ]
