# Generated by Django 4.1 on 2023-03-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attend",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="attend",
            name="total_time",
            field=models.IntegerField(null=True),
        ),
    ]
