# Generated by Django 4.1 on 2023-03-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attend",
            name="salary",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
