# Generated by Django 4.1 on 2023-03-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attend_end_time_alter_attend_total_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attend",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="attend",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
