# Generated by Django 4.1 on 2023-03-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attend_end_time_alter_attend_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attend",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="attend",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
