# Generated by Django 4.1 on 2023-03-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attend_end_time_alter_attend_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("event_name", models.CharField(max_length=50)),
            ],
        ),
    ]
