# Generated by Django 4.1 on 2023-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="attend",
            name="salary",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attend",
            name="total_time",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
